export const API_INPUTS = {
  login: '/auth/login',
  register: '/auth/register',
  logout: '/auth/logout',
  partOfSpeeches: '/partOfSpeeches',
  words: '/words',
  examples: '/examples',
  definitions: '/definitions',
  users: '/users',
  meanings: '/meanings',
  favorites: '/favorites',
  idioms: '/idioms',
  comments: '/comments',
  phonetics: '/phonetics',
}
